
server:
  port: 8091



eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

spring:
    application:
        name: config-server
    cloud:
        config:
          server:
            git:
              uri: https://github.com/li9503/carrots
              search-paths: respo
          label: master
        bus:
          enabled: true
          trace:
            enabled: true

    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh