server:
    port: 8083
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://193.112.201.68:8090/eureka/
  instance:
    hostname: localhost
