spring:
  application:
    name: service-uaa

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.153:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://193.112.201.68:8090/eureka/
